version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER:     medisecure
      POSTGRES_PASSWORD: medisecure_pass
      POSTGRES_DB:       medisecure_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medisecure"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://medisecure:medisecure_pass@db:5432/medisecure_db
      SECRET_KEY:   CHANGE_ME_TO_A_LONG_RANDOM_STRING_IN_PROD
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  scheduler:
    build: .
    command: python scheduler.py
    environment:
      DATABASE_URL: postgresql+asyncpg://medisecure:medisecure_pass@db:5432/medisecure_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
